networks:
  dev:

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/test
    environment:
      MONGO_INITDB_ROOT_USERNAME: kor
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    depends_on:
      - mongodb
    build:
      context: ./server
    networks:
      - dev

  frontend:
    build:
      context: ./front
    networks:
      - dev
volumes:
  mongodb_data:
