networks:
  dev:

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    container_name: my_mongodb
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - dev
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    depends_on:
      - mongodb
    build:
      context: ./server
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USERNAME
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DB_NAME
      - DB_PORT=$MONGODB_PORT
      - HOST=$HOST
    networks:
      - dev
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  frontend:
    depends_on:
      - backend
    build:
      context: ./front
    networks:
      - dev
    ports:
      - 8081:8081
volumes:
  db:
