networks:
  dev:

services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql8.0
    ports:
      - 3345:3306
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./mysql8.0/logs:/var/log/mysql:rw
      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./auto-generate:/auto-generate:rw
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./server
    networks:
      - dev

  frontend:
    build:
      context: ./front
    networks:
      - dev
